#!/command/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
    /config/{ssl,www,crowdsec,acme.sh} \
    /config/nginx/{site-confs,samples,conf.d} \
    /config/ssl/acme \
    /config/ssl/self-signed \
    /config/crontabs \
    /config/log/nginx \
    /run